### ISSUE TITLE
Screens opening new tab on form submit

### ISSUE THREAD

**Issue by jacobkeaton1** [fontaine-trailer/fdi-app#13]
Certain screens are opening new tabs when forms are submitted. All of this applications activity should take place within the same tab no new tabs other than for downloads.

**Comment by annacrombie** [comment]
can you tell me what specific screens are opening new tabs?
2017年10月23日(月) 14:44 jacobkeaton1 <notifications@github.com>:

**Comment by annacrombie** [comment]
I haven't been able to reproduce this on my computer.

**Comment by annacrombie** [comment]
bug is browser specific
