### ISSUE TITLE
Reports only show first entry for user

### ISSUE THREAD

**Issue by jacobkeaton1** [fontaine-trailer/fdi-app#6]
In a single period the report only shows the first entry that the user entered. This will cause issues when someone internally loads files for all dealers. Only the users first entry will be sum and entered on the report.

**Comment by jacobkeaton1** [comment]
@annacrombie I was trying to work my way through why only the first set of details was returned. Can I use the rails console to debug the database?

**Comment by annacrombie** [comment]
Yeah, you just refer to the models as classes.

```
2.4.0 :004 > User.first
 => #<User id: 1, name: "mabelle", admin: false, created_at: "2017-07-11 19:20:21", updated_at: "2017-07-16 17:40:40", password_digest: "$2a$10$zqYC3.SvJUAySCKo0A4NRuh7S8Mh8aID9LdZ8l6Wvzc...", email: "1212123123", token: "MouuFzJFvkeexgPohjrafnai"> 
2.4.0 :005 > User.first.name
 => mabelle
2.4.0 :006 > Detail.last.model
 => "rev-drop-53-rsa"

**Comment by annacrombie** [comment]
d623daa0d09ce3b3e003f765ed9e61384071a6ae
