### ISSUE TITLE
Upload button breaks on every upload

### ISSUE THREAD

**Issue by jacobkeaton1** [fontaine-trailer/fdi-app#7]
After uploading a file the upload functionality throws an error until user goes back in browser and re-uploads

**Comment by annacrombie** [comment]
the upload button works again after a refresh?

**Comment by annacrombie** [comment]
is the error message something like:
```
The change you wanted was rejected.

Maybe you tried to change something you didn't have access to.
```
?

**Comment by annacrombie** [comment]
okay, I think it should be fixed.  It was a bug with the CSRF token and Turbolinks not refreshing it.
840632c6f0d1ef5ececf6e9ab5703b7b1a197dd4

**Comment by annacrombie** [comment]
okay, I think it should be fixed.  It was a bug with the CSRF token and Turbolinks not refreshing it.
840632c6f0d1ef5ececf6e9ab5703b7b1a197dd4

**Comment by jacobkeaton1** [comment]
Sorry i didn't see these messages but yes that it is there error that was showing. Thanks for fixing.
